### ISSUE TITLE
Self closing DIV when using 'html' context

### ISSUE THREAD

**Issue by danchapman-pearson** [Adobe-Marketing-Cloud/htl-spec#22]
When I do:
`${'<div></div>' @context='html'}`

It outputs invalid HTML, it self-closes the element:
`<div/>`

Only a set number of elements are permitted to self-close - [http://xahlee.info/js/html5_non-closing_tag.html](http://xahlee.info/js/html5_non-closing_tag.html).

**Comment by raducotescu** [comment]
@danchapman-pearson, I think this issue refers to actually the Apache Sling implementation, specifically to https://issues.apache.org/jira/browse/SLING-5841. Since this is an implementation detail, with several workarounds, I'll close this issue as invalid, since it's not related to the actual language specification.
