### ISSUE TITLE
Label is not supported on data-sly-element

### ISSUE THREAD

**Issue by FrozenReality** [Adobe-Marketing-Cloud/htl-spec#28]
Label is not supported on data-sly-element even though it is valid html tag.

example code:

``` html
<div data-sly-element="${'label'}">
    foo
</div>
```

**Comment by paul-bjorkstrand** [comment]
I can understand why they didn't add label, since it typically needs a `for` attribute, which is not valid on a `<div>` or, if you are using the form `<label>Some Field: <input name="field"/></label>`, you (most likely) already know that the surrounding element needs to be a label.

Do you have a use case for why `data-sly-element` with a value of `label` is needed?

**Comment by FrozenReality** [comment]
I currently have a an element which can have 1 or more inputs. If it is one input I'd like to use `data-sly-element` to change my div to a label so when a user click it, the focus goes to the input. I however do not want to show this label when there are multiple inputs as a label should only have one input inside it.

**Comment by paul-bjorkstrand** [comment]
(Belated) follow-up, the best approach I see would be to use `data-sly-test` with an actual `<label>`. If you need the text in a div in the opposite case (multiple inputs), use the opposite expression in a `data-sly-test` with the same text in a `<div>`

In general, it is best practice to have a label for every form field.

**Comment by raducotescu** [comment]
This is documented in the [Display Context section](https://github.com/Adobe-Marketing-Cloud/htl-spec/blob/master/SPECIFICATION.md#121-display-context), for the `elementName` context, where there's a list of accepted elements.
